// Package mcpsession provides cryptographically unguessable, stateful MCP
// session identifiers for Streamable HTTP.
package mcpsession

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"sync"
	"sync/atomic"
)

// Option configures a Manager.
type Option func(*Manager)

// WithTerminationObserver registers cleanup invoked once when a session is
// successfully terminated.
func WithTerminationObserver(observer func(sessionID string)) Option {
	return func(manager *Manager) {
		manager.terminationObserver = observer
	}
}

// Manager implements server.SessionIdManager.
type Manager struct {
	secret              [32]byte
	counter             atomic.Uint64
	mu                  sync.RWMutex
	terminated          map[string]bool
	terminationObserver func(sessionID string)
}

// NewManager creates a session manager with a process-local random secret.
func NewManager(options ...Option) (*Manager, error) {
	manager := &Manager{
		terminated: make(map[string]bool),
	}
	for _, option := range options {
		option(manager)
	}
	if _, err := rand.Read(manager.secret[:]); err != nil {
		return nil, fmt.Errorf("generate MCP session secret: %w", err)
	}
	return manager, nil
}

// Generate creates and records a cryptographically unguessable session ID.
func (m *Manager) Generate() string {
	sequence := m.counter.Add(1)
	var input [40]byte
	copy(input[:32], m.secret[:])
	binary.BigEndian.PutUint64(input[32:], sequence)
	digest := sha256.Sum256(input[:])
	sessionID := base64.RawURLEncoding.EncodeToString(digest[:])

	m.mu.Lock()
	m.terminated[sessionID] = false
	m.mu.Unlock()
	return sessionID
}

// Validate verifies that a session ID was generated by this process.
func (m *Manager) Validate(sessionID string) (bool, error) {
	m.mu.RLock()
	terminated, ok := m.terminated[sessionID]
	m.mu.RUnlock()
	if !ok {
		return false, fmt.Errorf("unknown MCP session ID")
	}
	return terminated, nil
}

// Terminate marks a known session as terminated.
func (m *Manager) Terminate(sessionID string) (bool, error) {
	m.mu.Lock()
	terminated, ok := m.terminated[sessionID]
	if !ok {
		m.mu.Unlock()
		return false, fmt.Errorf("unknown MCP session ID")
	}
	if terminated {
		m.mu.Unlock()
		return false, nil
	}
	m.terminated[sessionID] = true
	observer := m.terminationObserver
	m.mu.Unlock()
	if observer != nil {
		observer(sessionID)
	}
	return false, nil
}
