// Package mcpsession provides cryptographically unguessable, stateful MCP
// session identifiers for Streamable HTTP.
package mcpsession

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"sync"
	"sync/atomic"
)

// Manager implements server.SessionIdManager.
type Manager struct {
	secret     [32]byte
	counter    atomic.Uint64
	mu         sync.RWMutex
	terminated map[string]bool
}

// NewManager creates a session manager with a process-local random secret.
func NewManager() (*Manager, error) {
	manager := &Manager{
		terminated: make(map[string]bool),
	}
	if _, err := rand.Read(manager.secret[:]); err != nil {
		return nil, fmt.Errorf("generate MCP session secret: %w", err)
	}
	return manager, nil
}

// Generate creates and records a cryptographically unguessable session ID.
func (m *Manager) Generate() string {
	sequence := m.counter.Add(1)
	var input [40]byte
	copy(input[:32], m.secret[:])
	binary.BigEndian.PutUint64(input[32:], sequence)
	digest := sha256.Sum256(input[:])
	sessionID := base64.RawURLEncoding.EncodeToString(digest[:])

	m.mu.Lock()
	m.terminated[sessionID] = false
	m.mu.Unlock()
	return sessionID
}

// Validate verifies that a session ID was generated by this process.
func (m *Manager) Validate(sessionID string) (bool, error) {
	m.mu.RLock()
	terminated, ok := m.terminated[sessionID]
	m.mu.RUnlock()
	if !ok {
		return false, fmt.Errorf("unknown MCP session ID")
	}
	return terminated, nil
}

// Terminate marks a known session as terminated.
func (m *Manager) Terminate(sessionID string) (bool, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.terminated[sessionID]; !ok {
		return false, fmt.Errorf("unknown MCP session ID")
	}
	m.terminated[sessionID] = true
	return false, nil
}
